### ISSUE TITLE
Exception with Chisel 2

### ISSUE THREAD

**Issue by ghost** [lawremi/PerFabricaAdAstra#32]
Hi,

I got the following exception with chisel 2 for cobblestone, Is this exception caused by PFAA or Chisel2?

[B#439]  net.minecraft.util.ReportedException: Rendering item
[B#439]     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1388) ~[blt.class:?]
[B#439]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990) ~[bao.class:?]
[B#439]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#439]     at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#439]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
[B#439]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#439]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#439]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
[B#439]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#439]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#439]  Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
[B#439]     at org.pfaa.block.CompositeBlock.getUnderlayIcon(CompositeBlock.java:51) ~[CompositeBlock.class:?]
[B#439]     at org.pfaa.block.CompositeBlock.func_149691_a(CompositeBlock.java:45) ~[CompositeBlock.class:?]
[B#439]     at net.minecraft.client.renderer.RenderBlocks.func_147787_a(RenderBlocks.java:9366) ~[blm.class:?]
[B#439]     at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:9278) ~[blm.class:?]
[B#439]     at org.pfaa.geologica.client.render.CompositeBlockItemRenderer.renderItem(CompositeBlockItemRenderer.java:34) ~[CompositeBlockItemRenderer.class:?]
[B#439]     at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183) ~[ForgeHooksClient.class:?]
[B#439]     at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563) ~[bny.class:?]
[B#439]     at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488) ~[GuiContainerManager.class:?]
[B#439]     at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270) ~[bex.class:?]
[B#439]     at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99) ~[bex.class:?]
[B#439]     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1354) ~[blt.class:?]
[B#439]     ... 9 more

**Comment by Krysinski** [comment]
Stones with different hardness and resistance cant be chiseled! Its issue for me now. When i disable cobblestone in chisel config i get client crash.
java.lang.NullPointerException: Rendering item
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:402)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_146977_a(GuiChisel.java:143)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1067)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:962)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:285)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:186)

**Comment by Krysinski** [comment]
Chisel configs must be same at server and client. Thats fix crash.

**Comment by lawremi** [comment]
Would you please clarify this? What do you mean by stones with different hardness and resistance can't be chiseled? The only chisable stones are marbel, limestone and granite. The crash issue has been resolved, right?

**Comment by Krysinski** [comment]
I mean that granite cobblestone with resistance 9 (hardness 3) cant be converted in diorite cobblestone with resistance 12 (hardness 4). Blastresistance of meterials is very important for building on hardcore-tech servers and diorite is more difficult to mine material as granite. Only blocks with same hardness/resistance can be chiseled i think.

**Comment by lawremi** [comment]
Please excuse my ignorance, but are you saying that Chisel allows conversion between stone types, but it's not working between granite and diorite? In terms of gameplay, I'm not sure that should even be allowed.

**Comment by Krysinski** [comment]
Yes! Chisel allows conversion between any cobblestones of geologica and also between std chisel's list of cobblestone. We try to get GT reg/black granite (need to craft reinforced bronze block) from PFAA Granite/Basalt (GT doesnt generate own granite with PFAA) with MT script and foud that GT granite have hardness 4,5 and resistance 32. Then we try to calculate both parametrs and quantity of PFAA stones to get in result few same parameters of GT granite. After all we found this issue. As i say, some way to fix that: disable cobblestone feature in Chisel2 conf.
Sorry, in russian language i speak more better)

**Comment by lawremi** [comment]
So what exactly do you want us to fix?

**Comment by Krysinski** [comment]
There is no issues fo me exclude this one: Chisel allows conversion between stone types.

**Comment by lawremi** [comment]
This is due to the ore dictionary. If I made an option to disable that, it wouldn't be a "real" fix either. Thus, I'm not sure there is a real fix.

**Comment by Krysinski** [comment]
Hm, i think about too, but find that stones (not cobblestones) in chisel has same oredict names but cant be converted. You need to chek this.
