### ISSUE TITLE
Fumaroles and Kimberlite pipes are inaccurate.

### ISSUE THREAD

**Issue by TheGurw** [lawremi/PerFabricaAdAstra#37]
![2015-01-22_12 42 47](https://cloud.githubusercontent.com/assets/801474/5861339/a4102a28-a225-11e4-8e15-ebdd4249545e.png)
^ Current generation of both Fumaroles and Kimberlite Pipes

Fumaroles and Kimberlite pipes are inaccurate.

* Fumaroles are not fumaroles unless they breach the surface of the earth.

From Wikipedia:
> A fumarole (Latin fumus, smoke) is an opening in a planet's crust, often in the neighborhood of volcanoes, which emits steam and gases such as carbon dioxide, sulfur dioxide, hydrogen chloride, and hydrogen sulfide.

To correct this issue, extend fumarole length in order to always breach the surface.

* Horizontal Kimberlite pipes are extremely rare in reality, to the point of "might as well pretend they don't exist."

![kimberlitepipes](https://cloud.githubusercontent.com/assets/801474/5861416/4452cfb8-a226-11e4-9679-07cc73250f2f.png)

From Wikipedia:
> ...carrot-shaped, vertical intrusions termed 'pipes'. This classic carrot shape is formed due to a complex intrusive process of kimberlitic magma which inherits a large proportion of CO2 (lower amounts of H2O) in the system, which produces a deep explosive boiling stage that causes a significant amount of vertical flaring...

To correct this issue, remove fumarole inheritance and if possible, create a funnel-shaped, wide, low density vein with the "motherlode" or "point" of the funnel below bedrock (since in reality this would be ~150 km below the surface). If the funnel shape is not possible, a simple wide cylinder would suffice. The pipes do not need to breach the surface but most of them should, and all of them should start from bedrock.

**Comment by lawremi** [comment]
I think making the kimberlite pipes more vertical makes sense. They are already near bedrock. I'm not sure I want them to extend to the surface, because diamonds are valuable. 

For the fumaroles, it's not feasible at the moment to make them extend to the surface (limitation of CustomOreGen). But I can raise them a bit. Instead of filling them with lava, I could create gas blocks for CO2, SO2 and H2S. Those would present interesting challenges.

**Comment by TheGurw** [comment]
```xml
<!-- ********************** ADD SULFUR TO FUMAROLES ********************** -->

    <ConfigSection>
      <VeinsPreset name="PresetSulfurFumarole"
                   inherits='PresetPipeVeins' seed='0xE222'
                   drawWireframe='false'>
        <WireframeColor>0x40000000</WireframeColor> 
        <Setting name='MotherlodeFrequency'
                 avg=':= 0.125 * _default_'/> 
        <Setting name='MotherlodeHeight'
                 avg=':= 20/64 * dimension.groundLevel' range='5'/>
            <Setting name='BranchInclination' avg='1.57' range='0.25' type='normal'/>
            <Setting name='BranchLength' avg='140' range='0'/>
        <OreBlock block='PFAAGeologica:weakOreRock:9' weight='0.1'/>
        <OreBlock block='PFAAGeologica:weakOreRock:11' weight='0.6'/>
        <OreBlock block='PFAAGeologica:weakOreRock:5' weight='0.3'/>
        <BiomeSet inherits='volcanic'/>
      </VeinsPreset>


     <VeinsPreset name="PresetSulfurFumaroleAir" block='minecraft:air'
                   inherits='PresetSulfurFumarole' seed='0xE222'
                   drawWireframe='false'>
        <WireframeColor>0x40FF0000</WireframeColor> 
        <Setting name='MotherlodeSize' avg=':= 1 * _default_'/>
        <Setting name='SegmentRadius' avg=':= 1 * _default_'/>
            <Setting name='OreDensity' avg='0.25' range='0'/>
        <ReplacesOre block='stone'/>
        <Replaces block='minecraft:dirt'/>
        <Replaces block='minecraft:water'/>
        <Replaces block='minecraft:gravel'/>
        <Replaces block='minecraft:grass'/>
        <Replaces block='Metallurgy:utility.ore:0'/>
      </VeinsPreset> 

      <VeinsPreset name="PresetSulfurFumaroleSulfur" block='Metallurgy:utility.ore:0'
                   inherits='PresetSulfurFumarole' seed='0xE222'
                   drawWireframe='false'>
        <WireframeColor>0x40FFFF00</WireframeColor> 
        <Setting name='MotherlodeSize' avg=':= 2 * _default_'/>
        <Setting name='SegmentRadius' avg=':= 8 * _default_'/>
            <Setting name='OreDensity' avg='1' range='0'/>
        <Replaces block='minecraft:dirt'/>
        <Replaces block='minecraft:gravel'/>
        <Replaces block='minecraft:grass'/>
      </VeinsPreset>
    </ConfigSection>



    <ConfigSection>
      <IfCondition condition=":=?GeologicaGenVolcanic &amp; ?GeologicaActive">
        <Veins name="SulfurFumarole" inherits='PresetSulfurFumarole'>
         <Veins name="SulfurFumaroleAir" inherits='PresetSulfurFumaroleAir'>
         <Veins name="SulfurFumaroleSulfur" inherits='PresetSulfurFumaroleSulfur'/>
	 </Veins>
        </Veins>
      </IfCondition>
    </ConfigSection>

<!-- ********************** END OF SULFUR TO FUMAROLES ********************** -->
```
This is how we're doing it. Seems to be working fine - Ignore the sulfur bit, we're using Metallurgy as well, but this brings them to the surface, punches a hole down the middle, and then replaces the area around the top with sulfur. As for the diamonds, I understand that they have more value in the general user's situation than ours, but surely a reduction in vein frequency would alleviate those concerns?

**Comment by lawremi** [comment]
That solution makes the veins quite large. While decreasing frequency is useful to retain balance, it does make it so you either have zero diamonds or stacks of diamonds.

**Comment by TheGurw** [comment]
No no, that setting is for the fumaroles, not Kimberlite pipes - we have a separate configuration for the Kimberlite pipes.
