### ISSUE TITLE
Vanilla Sandstone isn't being replaced by PFAA Sandstone

### ISSUE THREAD

**Issue by TheGurw** [lawremi/PerFabricaAdAstra#38]
![2015-01-26_19 47 19](https://cloud.githubusercontent.com/assets/801474/5912670/713628ce-a594-11e4-95de-7452cfde2bc9.png)

Not sure if this is intentional or not, but it's hella confusing to some players, especially when you can have two types of sandstone in one area.

If you need more information, please let me know.

**Comment by lawremi** [comment]
This is intentional. This type of sandstone is sort of a decorative block, and I didn't want to remove it from the game. While there could be some way to craft it, I wanted to keep vanilla sandstone as a desert-specific item in order to preserve any dependent gameplay mechanics.
