### ISSUE TITLE
Rendering improvements

### ISSUE THREAD

**Issue by lawremi** [lawremi/PerFabricaAdAstra#4]
Lots of negative feedback on the textures. Ideas:

* Ores should render as overlays, with the base texture borrowed from a nearby (whitelisted?) stone.
* Overlays should be randomized, possible via rotation.
* Stone textures should smoothly transition.

**Comment by aarondandy** [comment]
I like the current look for the most part. My only complaint is that it is hard to tell the difference between diorite and diorite brick.

**Comment by lawremi** [comment]
Thanks for the feedback. I'm going to close this one for now, since people seem generally happy.
