### ISSUE TITLE
Z-fighting

### ISSUE THREAD

**Issue by retep998** [lawremi/PerFabricaAdAstra#43]
The distance of the overlay textures from the base textures is so low that on some graphics configurations the depth buffer is not enough and z-fighting occurs between the layers.
![](http://puu.sh/fYVWr/7d1cb33b36.png)
If you could increase the distance between the overlay and the base texture it would help mitigate this issue.

**Comment by lawremi** [comment]
Is that a block being rendered in the world, or somewhere else, like in the inventory?

**Comment by retep998** [comment]
That's actually a screenshot from a barrel, but the issue also exists in the inventory. In the world the z-fighting barely occurs.

**Comment by lawremi** [comment]
Please reopen if this does not fix your issue.
