### ISSUE TITLE
Crash with new MystCraft version

### ISSUE THREAD

**Issue by Arrabal-** [lawremi/PerFabricaAdAstra#45]
After doing some additional investigation regarding a crash involving Custom Ore Generation and MystCraft I discovered that the crash was dependent on PFAA being installed.  I have reproduced the issue other issue reports here since I am not sure where the crash is occurring specifically.

Getting a crash to desktop during world profiling on an existing world using the latest MystCraft release (0.11.2.01).

Crash report: http://pastebin.com/QKgRfZ7q

From the crash report it looks like it is due to interactions between Mystcraft, and Custom Ore Generation. Crash report indicates that MystCraft, FastCraft, ATG, and Custom Ore Generation all could be involved. Had all of these mods working together with the following versions:

MystCraft 0.11.0.00
 FastCraft 1.19
 ATG 0.11.0
 Custom Ore Generation 1.2.18

Tried updated version of the above mods and also removed them one at a time (and tried different combinations of mods). Validated that MystCraft 0.11.2.01 works with:

FastCraft 1.19 & 1.21
 ATG 0.11.0 & 0.12.0

MystCraft 0.11.2.01 and Custom Ore Generation 1.2.18 result in crash. Removing Custom Ore Generation resolves crash issue. Not sure if this is on the MystCraft side or the Custom Ore Generation Side so I am reporting to both.

Per the request of XCompWiz I have provided the links to other issue posts as well as some additional detail and the fml client logs.

https://github.com/XCompWiz/Mystcraft-Issues/issues/57
https://github.com/lawremi/CustomOreGen/issues/64

Also, I did some further testing and reproduced the crash with minimal mods installed.  The installed mods are:

FastCraft 1.21
MystCraft 0.11.2.01
ATG 0.12.0
COG 1.2.18
Per Fabrica Ad Astra (PFAA) 0.2.23

PFAA adds a heavily customized ore generation configuration to COG and adds new ores, along with replacing all the vanilla stone and ore.  The crash only occurs when both COG and PFAA are installed with MystCraft 0.11.2.01.

Here are the log files, as requested (had to split into two pastebins to get around the size limit.  Part 1 goes through preInit):

Part 1:  http://pastebin.com/pwezyGZb
Part 2:  http://pastebin.com/dzskLKT9

**Comment by lawremi** [comment]
This is a problem with CustomOreGen and its deferred generation algorithm; closing this one.
