### ISSUE TITLE
Rotarycraft conflict

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [lawremi/PerFabricaAdAstra#46]
Is the fix for rotarycraft conflict still coming? :D

**Comment by lawremi** [comment]
I swear I will release it this weekend. Sorry!

**Comment by Ganjalf-Amsterdoom** [comment]
No problem, thank you for your time and thank you for your mod

**Comment by nightstalker6669** [comment]
i'm assuming this is to address this issue? http://pastebin.com/1d3g0pgs

**Comment by Ganjalf-Amsterdoom** [comment]
Exactly that, thank you nightstalker6669

**Comment by nightstalker6669** [comment]
ok cool, I was trying to add rotarycraft in and kept getting that error, i see the commits on the github, so hopefully there will be a proper build soon, as i tried building it myself, and the server is crashing for different reasons now. http://pastebin.com/M0WEeTaP

**Comment by lawremi** [comment]
Yep, working hard on this much of the day. There have been a lot of improvements beyond the Rotarycraft fix. And they need testing and fixing. The RC fix is simple, so I can fix that in a branch if need be, and release.

**Comment by nightstalker6669** [comment]
i know me, and probably a few others, would really appreciate a release of at least the RC fix. its kinda hindering me from introducing rotarycraft to my server atm.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you very much for your time lawremi.

**Comment by lawremi** [comment]
Latest series of commits should get us very close to a release. Will likely happen tonight.

**Comment by lawremi** [comment]
Fixed in new release, 0.2.24.
