### ISSUE TITLE
Realistic terrain Generation 

### ISSUE THREAD

**Issue by 31trainman** [lawremi/PerFabricaAdAstra#59]
Whenever I choose realistic terrain generation and create a world the stone and layers underneath are vanilla and modded but not your types.

Mod list:
  AdvancedSolarPanel-1.7.10-3.5.1
  AgriCraft-1.7.10-1.5.0
  AMT_Generators-1.7.10-1.4.2
  AppleMilkTea2-1.7.10_2.9m
  appliedenergistics2-rv3-beta-6
  ATG-1.7.10-0.12.0
  AtomicHealer-1.0.1
  BetterFps-1.0.1
  BiblioCraft[v1.11.5][MC1.7.10]
  BiblioWoods[Forestry][v1.7]
  BiblioWoods[Natura][v1.5]
  BigDoors-1.7.10-1.1.0
  BigReactors-0.4.3A
  buildcraft-7.1.20
  buildcraft-compat-7.1.6
  Carpenter's Blocks v3.3.7 - MC 1.7.10
  catwalks-2.0.4
  cfm-3.4.8-mc1.7.10
  Chisel2-2.5.1.44
  ChiselTones-1.7.10-1.0-3
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.3-327
  CustomOreGen-1.7.10-1.2.26
  DragonAPI 1.7.10 V16d
  Enchiridion 2-1.7.10-2.0.2a
  EnderCore-1.7.10-0.2.0.36_beta
  EnderIO-1.7.10-2.3.0.427_beta
  ExtraCells-1.7.10-2.3.14b197
  ExtraTiC-1.7.10-1.4.6
  Farseek-1.0.11
  fastcraft-1.23
  FlenixCitiesCore_[1.7.10]-0.16.1-b122
  FlenixCitiesFood_[1.7.10]-0.6
  FlenixCitiesResearch_[1.7.10]-0.4
  FlenixRoads_[1.7.10]-0.10.0-b40
  forestry_1.7.10-4.2.15.63
  ForgottenNature_1.7.19
  FrameCompanion-1.1
  Framez-1.7.10-0.2-32-hotfix-universal
  GardenStuff-1.7.10-1.7.0
  gases-1.7.10-1.6.7
  gasesFramework-1.7.10-1.2.4
  Guide-API-1.7.10-1.0.1-29
  IC2NuclearControl-2.3.4a
  IGW-Mod-1.7.10-1.1.12-34-universal
  ImmersiveEngineering-0.7.7
  immersiveintegration-0.6.8
  industrialcraft-2-2.2.821-experimental
  InventoryTweaks-1.59-dev-152
  IvToolkit-1.2
  JAFFA-1.72.13
  logisticspipes-0.9.3.128
  magneticraft-0.6.1-final
  malisisadvert-1.7.10-0.5.0
  malisiscore-1.7.10-0.14.3
  malisisdoors-1.7.10-1.13.2
  Mantle-1.7.10-0.3.2b
  Mariculture-Deluxe-1.7.10-1.3.0-6
  Mekanism-1.7.10-9.1.0.281
  MekanismGenerators-1.7.10-9.1.0.281
  MekanismTools-1.7.10-9.1.0.281
  MineFactoryReloaded-[1.7.10]2.8.1-174
  ModularPowersuits-0.11.0.300
  natura-1.7.10-2.2.1a2
  neiaddons-1.12.15.41-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.2
  NotEnoughIDs-1.4.2
  NotEnoughItems-1.7.10-1.0.5.120-universal
  NotEnoughResources-1.7.10-0.1.0-122
  Numina-0.4.0.131
  OpenComputers-MC1.7.10-1.6.2.12-universal
  OpenFM-1.7.10-0.1.0-34
  OpenPrinter-MC1.7.10-0.1.0.132
  OpenRadio-0.6.1
  OpenSecurity-1.7.10-1.0-37
  Pam's HarvestCraft 1.7.10Lb
  PFAA-1.7.10-0.2.29
  PlanetguyLib-1.9.1
  platforms-1.7.10-0.1.2
  Practical-Logistics-1.7.10-0.2.3
  ProjectBlue-1.1.6-mc1.7.10
  ProjectRed-1.7.10-4.7.0pre12.95-Base
  ProjectRed-1.7.10-4.7.0pre12.95-Compat
  ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
  ProjectRed-1.7.10-4.7.0pre12.95-Integration
  ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  ProjectRed-1.7.10-4.7.0pre12.95-World
  Railcraft_1.7.10-9.12.2.0
  Railcraft_Cosmetics-1.7.10-v1.6
  ReactorCraft 1.7.10 V16d
  RemainInMotion-2.8.9
  RotaryCraft 1.7.10 V16d
  RTG-1.7.10-1.1.1.4
  ShetiPhianCore-1.7.10-3.0.0
  SonarCore-1.7.10-1.1.2
  Streams-0.2
  TConstruct-1.7.10-1.8.8
  ThermalDynamics-[1.7.10]1.2.0-171
  ThermalExpansion-[1.7.10]4.1.4-247
  ThermalFoundation-[1.7.10]1.2.5-115
  TiCTooltips-mc1.7.10-1.2.5
  Traincraft-4.3.1_007
  VersionChecker-1.1.9
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.10-1.1.6
  YeGamolChattels-1.1.2
  zettaindustries-1.1-106
  Zora no Densha 1.7.10-0.8.0.2
  Ztones-1.7.10-2.2.1

Java 8 update 121
Mac OS X 10.12.3

**Comment by whichonespink44** [comment]
@31trainman Can you confirm that this is happening with only RTG & PFAA installed? I haven't tested RTG for compatibility with PFAA specifically, but this is the first bug report involving PFAA that I've seen, so... I suspect that it's another mod interfering somehow.

But if the problem still exists with only RTG & PFAA installed, then that's a different story.

**Comment by 31trainman** [comment]
I just ran a test with world type set to realistic and didn't get the pfaa stones etc
![2017-02-28_19 12 09](https://cloud.githubusercontent.com/assets/3371136/23441814/475e95e4-fdea-11e6-8774-4cbdf6ffc3be.png)

**Comment by lawremi** [comment]
Thanks, this is already fixed in git, and I'm working every day to get the new version out.

**Comment by 31trainman** [comment]
Np glad I could help.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I know this issue is over a year old, but it would really be helpful if we could get a .jar release with a hotfix or patch for this problem.

**Comment by bHXDgiuMa5yLHyC8** [comment]
@lawremi Thank you for still supporting PFAA users and updating the mod. I am not handy enough with minecraft modding to build it correctly from the source; could you please upload a .jar to curseforge or dropbox?

**Comment by lawremi** [comment]
I tried creating a curseforge project over the weekend but it has not yet appeared yet for some reason. Trying to figure out what happened.

**Comment by tomasbrod** [comment]
You can attach build if you create a release here, on github.

**Comment by lawremi** [comment]
Should be downloadable here:
https://minecraft.curseforge.com/projects/per-fabrica-ad-astra-geologica

**Comment by tomasbrod** [comment]
I tried to compile myself, but I could not get the environment set up. Apparently it does not work with latest versions of tools and I spent too much time finding which work so I gave up.

**Comment by lawremi** [comment]
It would help to know what you tried, and how it failed. It's supposed to be fairly self-contained, i.e., no need to use any external tools, except Java, which should be backwards compatible.

**Comment by tomasbrod** [comment]
Off topic. I allowed myself to move to #61
